from cv2 import FONT_HERSHEY_COMPLEX, FONT_HERSHEY_COMPLEX_SMALL, FONT_HERSHEY_DUPLEX, FONT_HERSHEY_TRIPLEX, FONT_HERSHEY_SIMPLEX, FONT_HERSHEY_SCRIPT_COMPLEX, FONT_HERSHEY_SCRIPT_SIMPLEX, FONT_HERSHEY_PLAIN, FONT_ITALIC

FONTS = {
    "FONT_HERSHEY_COMPLEX": FONT_HERSHEY_COMPLEX,
    "FONT_HERSHEY_COMPLEX_SMALL": FONT_HERSHEY_COMPLEX_SMALL,
    "FONT_HERSHEY_DUPLEX": FONT_HERSHEY_DUPLEX,
    "FONT_HERSHEY_TRIPLEX": FONT_HERSHEY_TRIPLEX,
    "FONT_HERSHEY_SIMPLEX": FONT_HERSHEY_SIMPLEX,
    "FONT_HERSHEY_SCRIPT_COMPLEX": FONT_HERSHEY_SCRIPT_COMPLEX,
    "FONT_HERSHEY_SCRIPT_SIMPLEX": FONT_HERSHEY_SCRIPT_SIMPLEX,
    "FONT_HERSHEY_PLAIN": FONT_HERSHEY_PLAIN,
    "FONT_ITALIC": FONT_ITALIC,
}
FONT_NAMES = list(FONTS.keys())